force-app/main/default/objects/Jira__c/Jira__c.object-meta.xml
<CustomObject>
    <label>Jira</label>
    <nameField>
        <label>Jira Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jiras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Jira__c/fields/Assignee__c.field-meta.xml
<CustomField>
    <fullName>Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Jiras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Jira__c/fields/Done_Status_Count__c.field-meta.xml
<CustomField>
    <fullName>Done_Status_Count__c</fullName>
    <label>Done Status Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Jira__c/fields/In_Progress_Status_Count__c.field-meta.xml
<CustomField>
    <fullName>In_Progress_Status_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>In Progress Status Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Jira__c/fields/In_QC_Status_Count__c.field-meta.xml
<CustomField>
    <fullName>In_QC_Status_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>In QC Status Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Jira__c/fields/Reporter__c.field-meta.xml
<CustomField>
    <fullName>Reporter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporter</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Jiras1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Jira__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>To Do</fullName>
                <default>true</default>
                <label>To Do</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>In QC</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Jira__c/fields/To_Do_Status_Count__c.field-meta.xml
<CustomField>
    <fullName>To_Do_Status_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>To Do Status Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Jira__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Epic</fullName>
                <default>true</default>
                <label>Epic</label>
            </value>
            <value>
                <fullName>Story</fullName>
            </value>
            <value>
                <fullName>Task</fullName>
            </value>
            <value>
                <fullName>Bug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TodoStatusCountTest.cls
@isTest
public class TodoStatusCountTest {
    @isTest
    /**
     * @description: create a new record with 'To Do' as its status, changed to 'In Progress' and back to 'To Do'; checking for increment of To_Do_Status_Count__c
     * @author: Diya Shrestha
     */
    static void testTodoStatusCountIncrement() {
        User  testUser1 = [SELECT Id FROM User WHERE Username = 'helloooosregmi48@gmail.com' LIMIT 1];
        User  testUser2 = [SELECT Id FROM User WHERE Username = 'aneitathapa28@mindful-otter-400oh5.com' LIMIT 1];
        
        Jira__c todo = new Jira__c(
            StartDate__c = Date.newInstance(2024, 02, 22),
            Name = 'Epic 1',
            Reporter__c = testUser1.Id,
            Assignee__c = testUser2.Id,
            Summary__c = 'Parent Epic Summary',
            Status__c = 'To Do',
            Type__c = 'Epic',
            To_Do_Status_Count__c = 0,
            In_Progress_Status_Count__c = 0,
            In_QC_Status_Count__c = 0,
            Done_Status_Count__c =0
        );
        insert todo;
        
        todo = [SELECT Id, To_Do_Status_Count__c FROM Jira__c WHERE Id = :todo.Id];
        System.assertEquals(1, todo.To_Do_Status_Count__c, 'TodoStatusCount should be initialized to 1');
        
        todo.Status__c = 'In Progress';
        todo.DueDate__c = Date.newInstance(2024, 03, 12);
        update todo;
        
        todo = [SELECT Id, To_Do_Status_Count__c FROM Jira__c WHERE Id = :todo.Id];
        System.assertEquals(1, todo.To_Do_Status_Count__c, 'TodoStatusCount should remain 1');
        
        todo.Status__c = 'To Do';
        update todo;
        
        todo = [SELECT Id, To_Do_Status_Count__c FROM Jira__c WHERE Id = :todo.Id];
        System.assertEquals(2, todo.To_Do_Status_Count__c, 'TodoStatusCount should be incremented to 2');
    }
}