force-app/main/default/objects/Jira__c/Jira__c.object-meta.xml
<CustomObject>
    <label>Jira</label>
    <nameField>
        <label>Jira Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jiras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Jira__c/fields/Days_In_Done__c.field-meta.xml
<CustomField>
    <fullName>Days_In_Done__c</fullName>
    <label>Days In Done</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Jira__c/fields/Days_In_InProgress__c.field-meta.xml
<CustomField>
    <fullName>Days_In_InProgress__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Days In InProgress</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Jira__c/fields/Days_In_InQC__c.field-meta.xml
<CustomField>
    <fullName>Days_In_InQC__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Days In InQC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Jira__c/fields/Days_In_To_Do__c.field-meta.xml
<CustomField>
    <fullName>Days_In_To_Do__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Days In To Do</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Jira__c/fields/Last_Done_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Done_Date__c</fullName>
    <label>Last Done Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Jira__c/fields/Last_In_Progress_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_In_Progress_Date__c</fullName>
    <label>Last In Progress Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Jira__c/fields/Last_In_QC_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_In_QC_Date__c</fullName>
    <label>Last In QC Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Jira__c/fields/Last_To_Do_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_To_Do_Date__c</fullName>
    <label>Last To Do Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Jira__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>To Do</fullName>
                <default>true</default>
                <label>To Do</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>In QC</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateJiraDaysScheduled.cls
public class UpdateJiraDaysScheduled implements Schedulable {
    public void execute(SchedulableContext sc) {
        List<Jira__c> jiraList = [SELECT Id, Status__c, Last_To_Do_Date__c, Last_In_Progress_Date__c, Last_In_QC_Date__c, Last_Done_Date__c,
                                         Days_In_To_Do__c, Days_In_InProgress__c, Days_In_InQC__c, Days_In_Done__c
                                    FROM Jira__c];
        
        List<Jira__c> jiraToUpdate = new List<Jira__c>();
        
        for (Jira__c jira : jiraList) {
            if (jira.Status__c == 'To Do' && jira.Last_To_Do_Date__c != null) {
                jira.Days_In_To_Do__c = (Integer)(jira.Last_To_Do_Date__c.daysBetween(Date.today()));
            } else if (jira.Status__c == 'In Progress' && jira.Last_In_Progress_Date__c != null) {
                jira.Days_In_InProgress__c = (Integer)(jira.Last_In_Progress_Date__c.daysBetween(Date.today()));
            } else if (jira.Status__c == 'In QC' && jira.Last_In_QC_Date__c != null) {
                jira.Days_In_InQC__c = (Integer)(jira.Last_In_QC_Date__c.daysBetween(Date.today()));
            } 
            
            jiraToUpdate.add(jira);
        }
        
        if (!jiraToUpdate.isEmpty()) {
            update jiraToUpdate;
        }
    }
}